### ISSUE TITLE
Overview of eye-tracking systems employed

### ISSUE THREAD

**Issue by msschreiner** [manybabies/mb2-analysis#126]
In order to create an overview of the different  eye-tracking systems employed by the labs for the supplemental material, I used the dataset_scheet.csv within the meta_data folder that we originally pulled from our Google Drive (MB2 Datasets List). However, some of the information provided seems incomplete or incorrect.

- [x] babylabMPIB_adults: Is EyeLink 1000 identical to EyeLink 1000 Plus?
- [x] babyLeidenEdu_toddlers: Did they really use two different eye-trackers? Tobii Pro Fusion/Tobii X3-120?
- [x] childdevlabAshoka_adults and childdevlabAshoka_toddlers: Sampling rate of 60 - 1200 Hz?
- [x] infantcogUBC_toddlers and SkidLSDLab_adults/_toddlers: Did they use the same SMI eye-tracker? SMI/ SMI Redn
- [x] MiniDundee_adults: What exact Tobii eye-tracker did they use? Tobii Pro?
- [x] Tobii Pro Fusion 120 Hz	and Tobii Pro Fusion 120Hz needs to be changed to one and the same spelling!
- [x] babyuniHeidelberg_adults/_toddlers: did the Tobii Pro Fusion really sample with 1200 Hz?

**Comment by lucie-zimmer** [comment]
1. I checked the EyeLink website and found that the EyeLink 1000 and EyeLink 1000 Plus are two different eye trackers, so I assume the eye-tracker information from babylabMPIB is correct.
2.  The lab confirmed in the [lab questionnaire](url) that they used Pro Fusion 120 Hz with all adults and the first 7 toddlers. With toddlers 8-18 they used Tobii X3-120.
3. I sent an email to childdevlabAshoka  and asked them to confirm their sampling rate.
4. infantcogUBC used: SMI RED250Mobile; I updated it on the GoogleDrive MB2 Dataset List.
5. I sent an email to MiniDundee and asked them to specify the name of the eye tracker they used.
6. I updated the GoogleDrive MB2 Dataset List accordingly.
