### ISSUE TITLE
sanity checks on tracker data

### ISSUE THREAD

**Issue by mcfrank** [manybabies/mb2-analysis#15]
it would be great to create a script called `data_integrity.Rmd` that reads in the measurements and creates a series of tests for a variety of things (e.g., the extremal values in #12). 

Some ideas:
- [ ] basic histograms of marginals (x distribution and y distribution) for eye-movements 
- [ ] density of eye-movements (e.g., 2d histogram)
- [ ] maybe plotting on sample frames of the animation? 

The hope for this markdown would be that we render this and see visually whether everything looks reasonable.

**Comment by yuen-francis** [comment]
@yuen-francis

**Comment by yuen-francis** [comment]
first draft of data_integrity.Rmd now available, pull request sent. Will be closing this issue once all functions needed for sanity checking is implemented.
